[package]
name = "nsn-p2p"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio = { workspace = true }
libp2p = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

nsn-types = { workspace = true }
